version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GITTestAZPP_2425Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_gittestazpp_2425.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GITTestAZPP_2425Project
    version: "1.0"
- serviceName: project.siqa_gittestazpp_2425.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GITTestAZPP_2425Project
    version: "1.0"
